import 'server-only';
import { createHash } from 'node:crypto';
import { z } from 'zod';

/**
 * A 32-byte key: either base64 of exactly 32 bytes, or any random string of
 * 32+ characters (e.g. generated by the hosting dashboard), which is hashed
 * to 32 bytes. Read it with `secretKey()`.
 */
const base64Key32 = z
  .string()
  .min(1, 'is required')
  .refine((v) => Buffer.from(v, 'base64').length === 32 || v.length >= 32, 'must be 32 bytes base64, or a random string of 32+ characters');

const schema = z.object({
  APP_ENV: z.enum(['development', 'staging', 'production']).default('development'),
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  APP_URL: z.url(),
  DATABASE_URL: z.string().startsWith('postgres'),
  TOTP_ENCRYPTION_KEY: base64Key32,
  IP_HASH_SALT: z.string().min(16, 'must be at least 16 characters'),
  /** 32 random bytes, base64. Derives private receipt links; never rotate unless compromised (old links would stop working). */
  TOKEN_SECRET: base64Key32,
  /** `local` stores files on disk (development/tests); `s3` uses S3-compatible storage (Cloudflare R2). */
  STORAGE_DRIVER: z.enum(['local', 's3']).default('local'),
  LOCAL_STORAGE_DIR: z.string().default('.storage'),
  S3_ENDPOINT: z.url().optional(),
  S3_REGION: z.string().default('auto'),
  S3_BUCKET: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  /** Public CDN base URL for media in the bucket (e.g. https://media.example.com). */
  MEDIA_PUBLIC_BASE_URL: z.url().optional(),
  /** WAYL merchant API key. Without it, checkout creates the order and the team collects payment manually. */
  WAYL_API_KEY: z.string().min(8).optional(),
  WAYL_API_BASE_URL: z.url().default('https://api.thewayl.com'),
  /** `test` creates WAYL test-mode links (no real money); production must use `live`. */
  WAYL_ENV: z.enum(['live', 'test']).default('test'),
  /** Cloudflare Turnstile (bot check on the guest form). Both set = on; both unset = off. */
  TURNSTILE_SITE_KEY: z.string().min(1).optional(),
  TURNSTILE_SECRET_KEY: z.string().min(1).optional(),
  /** Chromium used to render PDFs; defaults to Playwright's bundled browser (the Docker image sets /usr/bin/chromium). */
  CHROMIUM_PATH: z.string().optional(),
  /** Where the PDF renderer reaches this app's print pages; defaults to http://127.0.0.1:$PORT. */
  PRINT_ORIGIN: z.url().optional(),
  /** Shared secret for the scheduled reconciliation call (`POST /api/cron/reconcile-payments`). */
  CRON_SECRET: z.string().min(32).optional(),
}).superRefine((e, ctx) => {
  if (e.APP_ENV === 'production' && e.WAYL_API_KEY && e.WAYL_ENV !== 'live') {
    ctx.addIssue({ code: 'custom', path: ['WAYL_ENV'], message: 'must be live in production' });
  }
  if (Boolean(e.TURNSTILE_SITE_KEY) !== Boolean(e.TURNSTILE_SECRET_KEY)) {
    ctx.addIssue({ code: 'custom', path: ['TURNSTILE_SECRET_KEY'], message: 'set both TURNSTILE_SITE_KEY and TURNSTILE_SECRET_KEY, or neither' });
  }
  if (e.STORAGE_DRIVER === 's3') {
    for (const k of ['S3_ENDPOINT', 'S3_BUCKET', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY', 'MEDIA_PUBLIC_BASE_URL'] as const) {
      if (!e[k]) ctx.addIssue({ code: 'custom', path: [k], message: 'is required when STORAGE_DRIVER=s3' });
    }
  }
  if (e.APP_ENV !== 'development' && e.STORAGE_DRIVER === 'local') {
    ctx.addIssue({ code: 'custom', path: ['STORAGE_DRIVER'], message: 'must be s3 outside development' });
  }
});

export type Env = z.infer<typeof schema>;

let cached: Env | undefined;

/**
 * Validated server environment. Parsed lazily so `next build` does not need
 * production secrets, but the first request fails loudly if anything is missing.
 */
export function env(): Env {
  if (cached) return cached;
  // A variable left empty in the hosting dashboard means "not set", not "invalid".
  const parsed = schema.safeParse(Object.fromEntries(Object.entries(process.env).filter(([, v]) => v !== '')));
  if (!parsed.success) {
    const problems = parsed.error.issues.map((i) => `  ${i.path.join('.')}: ${i.message}`).join('\n');
    throw new Error(`Invalid environment configuration:\n${problems}`);
  }
  cached = parsed.data;
  return cached;
}

export const isProduction = () => env().APP_ENV === 'production';

/** The 32-byte key behind TOTP_ENCRYPTION_KEY or TOKEN_SECRET (see `base64Key32`). */
export function secretKey(name: 'TOTP_ENCRYPTION_KEY' | 'TOKEN_SECRET'): Buffer {
  const value = env()[name];
  const decoded = Buffer.from(value, 'base64');
  return decoded.length === 32 && decoded.toString('base64') === value ? decoded : createHash('sha256').update(value).digest();
}
