import 'server-only';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { env } from '@/server/env';

/** Keys are always generated by us: `<folder>/<uuid>.<ext>`. Anything else is rejected. */
const KEY_PATTERN = /^(images|audio|documents)\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(webp|mp3|pdf)$/;

export function isValidStorageKey(key: string) {
  return KEY_PATTERN.test(key);
}

function assertKey(key: string) {
  if (!isValidStorageKey(key)) throw new Error(`Invalid storage key: ${key}`);
}

export interface StorageDriver {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

class LocalDriver implements StorageDriver {
  constructor(private readonly dir: string) {}
  private file(key: string) {
    assertKey(key);
    return path.join(this.dir, key);
  }
  async put(key: string, body: Buffer) {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
  }
  async get(key: string) {
    const file = this.file(key);
    try {
      return await readFile(file);
    } catch {
      return null;
    }
  }
  async delete(key: string) {
    await rm(this.file(key), { force: true });
  }
}

class S3Driver implements StorageDriver {
  private client: S3Client;
  constructor(private readonly bucket: string, endpoint: string, region: string, accessKeyId: string, secretAccessKey: string) {
    this.client = new S3Client({ endpoint, region, credentials: { accessKeyId, secretAccessKey } });
  }
  async put(key: string, body: Buffer, contentType: string) {
    assertKey(key);
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
        // Keys are content-unique (new uuid per upload), so they can be cached forever.
        CacheControl: 'public, max-age=31536000, immutable',
      }),
    );
  }
  async get(key: string) {
    assertKey(key);
    try {
      const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
      return res.Body ? Buffer.from(await res.Body.transformToByteArray()) : null;
    } catch {
      return null;
    }
  }
  async delete(key: string) {
    assertKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

let driver: StorageDriver | undefined;

export function storage(): StorageDriver {
  if (driver) return driver;
  const e = env();
  driver =
    e.STORAGE_DRIVER === 's3'
      ? new S3Driver(e.S3_BUCKET!, e.S3_ENDPOINT!, e.S3_REGION, e.S3_ACCESS_KEY_ID!, e.S3_SECRET_ACCESS_KEY!)
      : new LocalDriver(path.resolve(process.cwd(), e.LOCAL_STORAGE_DIR));
  return driver;
}

/** Public URL for a stored file (CDN in production, `/media/...` locally). */
export function publicMediaUrl(key: string): string {
  const e = env();
  return e.STORAGE_DRIVER === 's3' ? `${e.MEDIA_PUBLIC_BASE_URL!.replace(/\/$/, '')}/${key}` : `/media/${key}`;
}
