/**
 * Scans `themes/<key>/v<N>/manifest.ts` and writes `src/theme-registry/generated.ts`.
 * Adding a theme = adding a folder; no hand-edited registration anywhere.
 * Fails (and so fails dev/build/CI) if any manifest is invalid.
 */
import { readdirSync, existsSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { manifestSchema, codeRef } from '../src/theme-sdk/manifest';

const root = path.resolve(import.meta.dirname, '..');
const themesDir = path.join(root, 'themes');
const outFile = path.join(root, 'src/theme-registry/generated.ts');

const entries: { key: string; version: number; importPath: string }[] = [];
const errors: string[] = [];

for (const key of existsSync(themesDir) ? readdirSync(themesDir).sort() : []) {
  const themeDir = path.join(themesDir, key);
  if (key.startsWith('.') || !readdirSync(themeDir, { withFileTypes: true }).length) continue;
  for (const dirent of readdirSync(themeDir, { withFileTypes: true })) {
    if (!dirent.isDirectory()) continue;
    const match = /^v(\d+)$/.exec(dirent.name);
    if (!match) {
      errors.push(`themes/${key}/${dirent.name}: version folders must be named v1, v2, …`);
      continue;
    }
    const manifestPath = path.join(themeDir, dirent.name, 'manifest.ts');
    if (!existsSync(manifestPath)) {
      errors.push(`themes/${key}/${dirent.name}: missing manifest.ts`);
      continue;
    }
    const mod = await import(pathToFileURL(manifestPath).href);
    const parsed = manifestSchema.safeParse(mod.default);
    if (!parsed.success) {
      errors.push(`themes/${key}/${dirent.name}/manifest.ts:\n  ${parsed.error.issues.map((i) => `${i.path.join('.')} ${i.message}`).join('\n  ')}`);
      continue;
    }
    if (parsed.data.key !== key || parsed.data.version !== Number(match[1])) {
      errors.push(`themes/${key}/${dirent.name}: manifest says ${codeRef(parsed.data)}; it must match its folder`);
      continue;
    }
    entries.push({ key, version: parsed.data.version, importPath: `../../themes/${key}/${dirent.name}/manifest` });
  }
}

if (errors.length) {
  console.error(`Theme registry errors:\n${errors.join('\n')}`);
  process.exit(1);
}

entries.sort((a, b) => a.key.localeCompare(b.key) || a.version - b.version);
const source = `// GENERATED by scripts/generate-theme-registry.ts — do not edit. Regenerated on dev/build/test.
import type { ThemeManifest } from '@/theme-sdk/manifest';
${entries.map((e, i) => `import m${i} from '${e.importPath}';`).join('\n')}

export const generatedManifests: ThemeManifest[] = [${entries.map((_, i) => `m${i}`).join(', ')}];
`;
if (!existsSync(outFile) || readFileSync(outFile, 'utf8') !== source) writeFileSync(outFile, source);
console.log(`Theme registry: ${entries.length} theme version(s).`);
