import type { ThemeLocale } from '@/theme-sdk/format';

/**
 * The theme's own fixed wording. Customer content (names, message, venue…)
 * always comes from fields. Kurdish (ckb/bdn) shows Arabic until the owner
 * approves translations (docs/translations/KURDISH_REVIEW.md).
 */
const ar = {
  open: 'افتح الدعوة',
  openHint: 'اضغط لفتح علبة الدعوة',
  basmala: 'بسم الله الرحمن الرحيم',
  and: 'و',
  namesLabel: 'العروسان',
  date: 'التاريخ',
  time: 'الوقت',
  venue: 'المكان',
  countdownTitle: 'يبدأ الحفل بعد',
  days: 'يوم',
  hours: 'ساعة',
  minutes: 'دقيقة',
  countdownDone: 'حان موعد الفرح',
  map: 'افتح الموقع على الخريطة',
  opensNewTab: '(يفتح في نافذة جديدة)',
  formTitle: 'تأكيد الحضور',
  formIntro: 'يسعدنا أن نعرف إن كنت ستشاركنا فرحتنا.',
  guestName: 'اسمك',
  guestNamePlaceholder: 'الاسم الكامل',
  attendance: 'هل ستحضر؟',
  attending: 'سأحضر بإذن الله',
  notAttending: 'أعتذر عن الحضور',
  message: 'رسالتك للعروسين',
  messageOptional: '(اختياري)',
  messagePlaceholder: 'اكتب تهنئتك هنا',
  send: 'إرسال الرد',
  sending: 'جارٍ الإرسال…',
  successTitle: 'شكرًا لك',
  successBody: 'تم إرسال ردك إلى العروسين.',
  errRequiredName: 'يرجى كتابة اسمك.',
  errTooLongName: 'الاسم أطول من المسموح.',
  errRequiredAttending: 'يرجى اختيار الحضور أو الاعتذار.',
  errTooLongMessage: 'الرسالة أطول من ٥٠٠ حرف.',
  errForm: 'تعذّر إرسال الرد. يرجى المحاولة مرة أخرى.',
  errClosed: 'انتهت فترة الردود على هذه الدعوة.',
  errRateLimited: 'محاولات كثيرة. يرجى المحاولة بعد قليل.',
  charsLeft: 'حرفًا متبقيًا',
  closing: 'شكرًا لمشاركتكم فرحتنا',
  closingSub: 'حضوركم يتمّ سعادتنا',
  musicOn: 'إيقاف الموسيقى',
  musicOff: 'تشغيل الموسيقى',
  // Print card
  printInvite: 'يتشرفان بدعوتكم لحضور حفل زفافهما',
  printScan: 'امسح الرمز لفتح الدعوة',
  // Keepsake
  keepsakeTitle: 'رسائل المحبة',
  keepsakeSubtitle: 'تهاني الأهل والأحبة',
  keepsakeEmpty: 'لم تصل رسائل بعد.',
  keepsakeClosing: 'مع خالص الشكر لكل من شاركنا الفرح',
  page: 'صفحة',
} as const;

export type Copy = { [K in keyof typeof ar]: string };

const en: Copy = {
  open: 'Open invitation',
  openHint: 'Tap to open the invitation box',
  basmala: 'In the name of Allah, the Most Gracious, the Most Merciful',
  and: '&',
  namesLabel: 'The couple',
  date: 'Date',
  time: 'Time',
  venue: 'Venue',
  countdownTitle: 'The celebration begins in',
  days: 'days',
  hours: 'hours',
  minutes: 'minutes',
  countdownDone: 'The celebration has begun',
  map: 'Open location on the map',
  opensNewTab: '(opens in a new tab)',
  formTitle: 'Kindly reply',
  formIntro: 'We would love to know if you can join us.',
  guestName: 'Your name',
  guestNamePlaceholder: 'Full name',
  attendance: 'Will you attend?',
  attending: 'Joyfully attending',
  notAttending: 'Regretfully declining',
  message: 'Your message to the couple',
  messageOptional: '(optional)',
  messagePlaceholder: 'Write your wishes here',
  send: 'Send reply',
  sending: 'Sending…',
  successTitle: 'Thank you',
  successBody: 'Your reply has been sent to the couple.',
  errRequiredName: 'Please enter your name.',
  errTooLongName: 'The name is too long.',
  errRequiredAttending: 'Please choose attending or not attending.',
  errTooLongMessage: 'The message is longer than 500 characters.',
  errForm: 'Your reply could not be sent. Please try again.',
  errClosed: 'Replies for this invitation have closed.',
  errRateLimited: 'Too many attempts. Please try again shortly.',
  charsLeft: 'characters left',
  closing: 'Thank you for sharing our joy',
  closingSub: 'Your presence completes our happiness',
  musicOn: 'Turn music off',
  musicOff: 'Turn music on',
  printInvite: 'request the honour of your presence at their wedding',
  printScan: 'Scan to open the invitation',
  keepsakeTitle: 'Messages of love',
  keepsakeSubtitle: 'Wishes from family and friends',
  keepsakeEmpty: 'No messages yet.',
  keepsakeClosing: 'With heartfelt thanks to everyone who shared our joy',
  page: 'Page',
};

export function copyFor(locale: ThemeLocale): Copy {
  return locale === 'en' ? en : ar;
}
